### PR TITLE
ebs/ami_deprecation: don't crash when AMIs are nil

### LINKED ISSUE #224: AMI deprecation step fails when `skip_create_ami` is true
#### Overview of the Issue

Using the newest version of Packer and the AWS EBS plugin, the EBS plugin spews out an error that begins with `unexpected EOF`, but is really related to the `stepEnableDeprecation` call.

~~I _think_ the error might be related to the fact that the AMI I am using as a base (`base-ami`) already has the `DeprecationTime` field set. So when this new AMI tries to do the same, it receives an error.~~

_**UPDATE:**_ I'll try and isolate the root issue with test Packer configs.

```
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: panic: interface conversion: interface {} is nil, not map[string]string
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: goroutine 369 [running]:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*stepEnableDeprecation).Run(0xc000399290, {0x24730f5, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/step_enable_deprecation.go:25 +0x3ae
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000562e70, {0x27e4848, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/multistep/basic_runner.go:70 +0x2fe
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*Builder).Run(0xc0003d8a80, {0x27e4848, 0xc0008140c0}, {0x27ebdf0, 0xc0005623c0}, {0x27c2b60, 0xc0004360a0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/builder.go:410 +0x268c
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc0001410c0, 0x6ae040, 0xc0006ae020)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/rpc/builder.go:117 +0x1e3
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.call({0xc00009c660, 0xc00000e208, 0x13}, {0x246cd79, 0x4}, {0xc000571ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:556 +0x845
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.Call({0xc00009c660, 0xc00000e208, 0xc00007f200}, {0xc000474ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:339 +0xc5
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: net/rpc.(*service).call(0xc000141100, 0xc000047858, 0x0, 0xc000046ca0, 0xc000054700, 0x18bb985, {0x20246c0, 0xc0006ae01c, 0x18bb906}, {0x1fe6fe0, ...}, ...)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:377 +0x239
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:474 +0x405
```

#### Reproduction Steps

I'm still trying to isolate the cause of this problem. This does not happen when I build a base AMI using the Ubuntu 22.04 LTS image as a source. However, it *does* happen when I use the base AMI as a source.

In other words:

```
Ubuntu 22.04 - OK > Base AMI - Not OK -> New AMI
```

### Plugin and Packer version

- Packer version: `Packer v1.8.1`
- The `packer-plugin-amazon` version: `packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64`

### Simplified Packer Buildfile

See ***Reproduction Steps*** above.

### Operating system and Environment details

- OS `uname`: `Darwin <machine-id> 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64` => aka *macOS Big Sur 11.6.6*

### Log Fragments and crash.log files

<details>
<summary>Panic error output</summary>

```
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: panic: interface conversion: interface {} is nil, not map[string]string
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: goroutine 369 [running]:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*stepEnableDeprecation).Run(0xc000399290, {0x24730f5, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/step_enable_deprecation.go:25 +0x3ae
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000562e70, {0x27e4848, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/multistep/basic_runner.go:70 +0x2fe
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*Builder).Run(0xc0003d8a80, {0x27e4848, 0xc0008140c0}, {0x27ebdf0, 0xc0005623c0}, {0x27c2b60, 0xc0004360a0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/builder.go:410 +0x268c
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc0001410c0, 0x6ae040, 0xc0006ae020)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/rpc/builder.go:117 +0x1e3
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.call({0xc00009c660, 0xc00000e208, 0x13}, {0x246cd79, 0x4}, {0xc000571ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:556 +0x845
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.Call({0xc00009c660, 0xc00000e208, 0xc00007f200}, {0xc000474ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:339 +0xc5
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: net/rpc.(*service).call(0xc000141100, 0xc000047858, 0x0, 0xc000046ca0, 0xc000054700, 0x18bb985, {0x20246c0, 0xc0006ae01c, 0x18bb906}, {0x1fe6fe0, ...}, ...)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:377 +0x239
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:474 +0x405
```

</details>

- GitHub gist of the full build log with trace logging: https://gist.github.com/sc250024/a02ab45677f5f34f1ceddbc90f679541

### PR DESCRIPTION
**Pull request by lbajolet-hashicorp**
When a build file specifies a deprecation time on an AMI, and includes
the skip_create_ami directive in the configuration, the AMI map ends up
not being created in the state for the build, causing the depreciation
step to panic on an interface conversion.

This commit avoids such a problem by checking if the AMI map is indeed a
map and not nil before proceeding.
If it is not the expected type, we stop the build.

Closes #224

### CODE REVIEW

File: builder/ebs/step_enable_deprecation.go [hunk 1]
```diff
@@ -22,7 +22,12 @@ func (s *stepEnableDeprecation) Run(ctx context.Context, state multistep.StateBa
 	}
 
 	ec2conn := state.Get("ec2").(*ec2.EC2)
-	amis := state.Get("amis").(map[string]string)
+	amis, ok := state.Get("amis").(map[string]string)
+	if !ok {
+		ui.Error("no AMIs to depreciate")
+		ui.Error("make sure you did not include the `skip_create_ami' directive in the build")
+		return multistep.ActionHalt
```
Comment (nywilken) [inline builder/ebs/step_enable_deprecation.go:29]: A hard failure if no amis are in state sounds right. I think we can error on the type conversion error, and provide a check higher up specifically for the AMISkipCreateImage. 

```
// See builder/common/step_ami_region_copy.go for an example on how this information is being passed in. 
 if s.AMISkipCreateImage {
 69     ui.Say("Skipping Enable AMI deprecation because skip_create_ami is true")
 70     return multistep.ActionContinue
 71   }
```


```suggestion
		err := fmt.Errorf("no AMIs found in state to depreciate")
		state.Put("error", err)
		ui.Error(err.Error()
		return multistep.ActionHalt
```
By putting error into the state Packer will bubble the error upstream and include it as a final error for the failed build. Which will ensure it gets displayed as the cause for the failed build.

**Review by nywilken — COMMENTED** [review]
Few small suggestions. A hard failure when skip_ami_create is inconsistent with how other steps work for the plugin. So I left a suggestion to handle the skip create check separately.

File: builder/ebs/step_enable_deprecation.go (hunk 1 above)
Comment (lbajolet-hashicorp) [reply builder/ebs/step_enable_deprecation.go:29]: I agree with the check higher up, so the rest of the build can continue if the command is invoked with skip_ami for testing purposes.
I've implemented your suggestion, I'll get to the check in a separate commit

**Comment by sc250024** [comment]
Thank you for fixing this! I was tearing my hair out trying to figure out why my AMI builds were failing.

**Review by sc250024 — CHANGES_REQUESTED** [review]

File: builder/ebs/step_enable_deprecation.go [hunk 2]
```diff
@@ -22,7 +22,13 @@ func (s *stepEnableDeprecation) Run(ctx context.Context, state multistep.StateBa
 	}
 
 	ec2conn := state.Get("ec2").(*ec2.EC2)
-	amis := state.Get("amis").(map[string]string)
+	amis, ok := state.Get("amis").(map[string]string)
+	if !ok {
+		err := fmt.Errorf("no AMIs found in state to depreciate")
```
[the remark this answers is not in the document]
Comment (lbajolet-hashicorp) [reply builder/ebs/step_enable_deprecation.go]: You're right, it's fixed now, thanks!

**Review by nywilken — APPROVED** [review]
Nice! Changes look good to me. Feel free to merge when ready.
